apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: employee-app
        image: aakansha113/employee-management-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root123
        - name: DB_NAME
          value: employee_db

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
