apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS employee_db;
    USE employee_db;

    CREATE TABLE IF NOT EXISTS employees (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100),
      role VARCHAR(100)
    );

    INSERT INTO employees (name, role) VALUES
    ('Aakansha', 'DevOps Engineer'),
    ('Test User', 'Engineer');
